# ---
# - name: Configure network devices
#   hosts: all
#   gather_facts: no
#   connection: network_cli
#   tasks:
    # - name: Configure IP of Gateway
    #   ios_l3_interfaces:
    #     config:
    #       - name: GigabitEthernet0/1
    #         ipv4:
    #           - address: 10.0.1.1/30
    #       - name: GigabitEthernet0/2
    #         ipv4:
    #           - address: 10.0.1.5/30
    #     state: merged
    # # - name: configure g0/0 of Gateway
    # #   ios_config:
    # #     lines:
    # #       - ip address dhcp
    # #       - no shutdown
    # #     parents: interface GigabitEthernet0/0
    # - name: Configure ospf of Gateway
    #   ios_config:
    #     lines:
    #       - network 10.0.1.0 0.0.0.3 area 0
    #       - network 10.0.1.4 0.0.0.3 area 0
    #       - network 10.0.99.0 0.0.0.255 area 0
    #     parents: router ospf 1
    # - name: No shutdown interfaces of Gateway
    #   ios_command:
    #     commands:
    #       - configure terminal
    #       - interface GigabitEthernet0/1
    #       - no shutdown
    #       - interface GigabitEthernet0/2
    #       - no shutdown
    #       - interface GigabitEthernet0/2.10
    #       - no shutdown
    #       - encapsulation dot1q 10
    #       - ip address 10.0.10.1 255.255.255.0
    #       - interface GigabitEthernet0/2.20
    #       - no shutdown
    #       - encapsulation dot1q 20
    #       - ip address 10.0.20.1 255.255.255.0
    # - name: Configure IP of Router 1
    #   ios_l3_interfaces:
    #     config:
    #       - name: GigabitEthernet1
    #         ipv4:
    #           - address: 10.0.1.2/30
    #       - name: GigabitEthernet2
    #         ipv4:
    #           - address: 10.0.1.9/30
    #     state: overridden
    # - name: Configure ospf of Router 1
    #   ios_config:
    #     lines:
    #       - network 10.0.1.0 0.0.0.3 area 0
    #       - network 10.0.1.8 0.0.0.3 area 0
    #       - network 10.0.99.0 0.0.0.255 area 0
    #     parents: router ospf 1
    # - name: No shutdown interfaces of Router 1
    #   ios_command:
    #     commands:
    #       - interface GigabitEthernet1
    #       - no shutdown
    #       - interface GigabitEthernet2
    #       - no shutdown
    #       - interface GigabitEthernet3
    #       - no shutdown

    # - name: Configure IP of Router 2
    #   ios_l3_interfaces:
    #     config:
    #       - name: GigabitEthernet1
    #         ipv4:
    #           - address: 10.0.1.6/30
    #       - name: GigabitEthernet2
    #         ipv4:
    #           - address: 10.0.1.10/30
    #     state: overridden
    # - name: Configure ospf of Router 2
    #   ios_config:
    #     lines:
    #       - network 10.0.1.4 0.0.0.3 area 0
    #       - network 10.0.1.8 0.0.0.3 area 0
    #       - network 10.0.99.0 0.0.0.255 area 0
    #     parents: router ospf 1
    # - name: No shutdown interfaces of Router 2
    #   ios_command:
    #     commands:
    #       - interface GigabitEthernet1
    #       - no shutdown
    #       - interface GigabitEthernet2
    #       - no shutdown
    #       - interface GigabitEthernet3
    #       - no shutdown
        
    # - name: Configure vlan 10, 20 of switch 1
    #   ios_vlans:
    #     config:
    #       - name: vlan10
    #         vlan_id: 10
    #       - name: vlan20
    #         vlan_id: 20
    #     state: merged

    # - name: Configure trunk port of switch 1
    #   ios_l2_interfaces:
    #     config:
    #       - name: GigabitEthernet0/0
    #         mode: trunk
    #         trunk:
    #           encapsulation: dot1q
    #         access:
    #       - name: GigabitEthernet0/1
    #     state: merged

    # - name: Configure vlan 10, 20 of switch 2
    #   ios_vlans:
    #     config:
    #       - name: vlan10
    #         vlan_id: 10
    #       - name: vlan20
    #         vlan_id: 20
    #     state: merged

    # - name: Configure trunk port of switch 2
    #   ios_l2_interfaces:
    #     config:
    #       - name: GigabitEthernet0/1
    #         mode: trunk
    #         trunk:
    #           encapsulation: dot1q
    #         access:
    #       - name: GigabitEthernet0/2
    #         mode: trunk
    #         trunk:
    #           encapsulation: dot1q
    #       - name: GigabitEthernet0/2
    #         mode: trunk
    #         trunk:
    #           encapsulation: dot1q
    #     state: merged
