---
- name: Configure routers
  hosts: routers
  gather_facts: no
  connection: network_cli
  tasks:
    - name: Configure IP of Gateway
      ios_l3_interfaces:
        config:
          - name: GigabitEthernet0/1
            ipv4:
              - address: 10.0.1.1/30
        state: merged
      when: inventory_hostname == "gateway"
    - name: configure g0/0 of Gateway
      ios_config:
        lines:
          - ip address dhcp
          - no shutdown
        parents: interface GigabitEthernet0/0
      when: inventory_hostname == "gateway"
    - name: Configure ospf of Gateway
      ios_config:
        lines:
          - network 10.0.1.0 0.0.0.3 area 0
          - network 192.168.122.0 0.0.0.255 area 0
        parents: router ospf 1 vrf data
      when: inventory_hostname == "gateway"
    - name: No shutdown interface of Gateway
      ios_command:
        commands:
          - configure terminal
          - interface GigabitEthernet0/1
          - no shutdown
      when: inventory_hostname == "gateway"

    - name: Configure IP of Router 1
      ios_l3_interfaces:
        config:
          - name: GigabitEthernet1
            ipv4:
              - address: 10.0.1.2/30
        state: merged
      when: inventory_hostname == "router1"
    - name: Configure ospf of Router 1
      ios_config:
        lines:
          - network 10.0.1.0 0.0.0.3 area 0
          - network 192.168.10.0 0.0.0.255 area 0
          - network 192.168.20.0 0.0.0.255 area 0
          - network 192.168.30.0 0.0.0.255 area 0
        parents: router ospf 1 vrf data
      when: inventory_hostname == "router1"
    - name: No shutdown interfaces and create sub-interfaces of Router 1
      ios_command:
        commands:
          - configure terminal
          - interface GigabitEthernet1
          - no shutdown
          - interface GigabitEthernet2
          - no shutdown
          - interface GigabitEthernet3
          - no shutdown
          - interface GigabitEthernet2.10
          - no shutdown
          - encapsulation dot1q 10
          - ip address 192.168.10.1 255.255.255.0
          - vrf forwarding data
          - interface GigabitEthernet2.20
          - no shutdown
          - encapsulation dot1q 20
          - ip address 192.168.20.1 255.255.255.0
          - vrf forwarding data
          - interface GigabitEthernet3.30
          - no shutdown
          - encapsulation dot1q 30
          - ip address 192.168.30.1 255.255.255.0
          - vrf forwarding data
      when: inventory_hostname == "router1"
    - name: Configure DHCP server
      ios_config:
        lines:
          - network 192.168.30.0 255.255.255.0
          - default-router 192.168.30.1
        parents: ip dhcp pool POOL
      when: inventory_hostname == "router1"
