---
- name: Configure routers
  hosts: routers
  gather_facts: no
  connection: network_cli
  tasks:
    - name: Configure IP of Gateway
      ios_l3_interfaces:
        config:
          - name: GigabitEthernet0/1
            ipv4:
              - address: 10.0.1.1/30
          - name: GigabitEthernet0/2
            ipv4:
              - address: 10.0.1.5/30
        state: merged
      when: inventory_hostname == "gateway"
    - name: configure g0/0 of Gateway
      ios_config:
        lines:
          - ip address dhcp
          - no shutdown
        parents: interface GigabitEthernet0/0
      when: inventory_hostname == "gateway"
    - name: Configure ospf of Gateway
      ios_config:
        lines:
          - network 10.0.1.0 0.0.0.3 area 0
          - network 10.0.1.4 0.0.0.3 area 0
          - network 10.0.99.0 0.0.0.255 area 0
        parents: router ospf 1
    - name: No shutdown interfaces of Gateway
      ios_command:
        commands:
          - configure terminal
          - interface GigabitEthernet0/1
          - no shutdown
          - interface GigabitEthernet0/2
          - no shutdown
          - interface GigabitEthernet0/2.10
          - no shutdown
          - encapsulation dot1q 10
          - ip address 10.0.10.1 255.255.255.0
          - interface GigabitEthernet0/2.20
          - no shutdown
          - encapsulation dot1q 20
          - ip address 10.0.20.1 255.255.255.0
      when: inventory_hostname == "gateway"

    - name: Configure IP of Router 1
      ios_l3_interfaces:
        config:
          - name: GigabitEthernet1
            ipv4:
              - address: 10.0.1.2/30
          - name: GigabitEthernet2
            ipv4:
              - address: 10.0.1.9/30
        state: merged
      when: inventory_hostname == "router1"
    - name: Configure ospf of Router 1
      ios_config:
        lines:
          - network 10.0.1.0 0.0.0.3 area 0
          - network 10.0.1.8 0.0.0.3 area 0
          - network 10.0.99.0 0.0.0.255 area 0
        parents: router ospf 1
      when: inventory_hostname == "router1"

    - name: No shutdown interfaces of Router 1
      ios_command:
        commands:
          - interface GigabitEthernet1
          - no shutdown
          - interface GigabitEthernet2
          - no shutdown
          - interface GigabitEthernet3
          - no shutdown
      when: inventory_hostname == "router1"

    - name: Configure IP of Router 2
      ios_l3_interfaces:
        config:
          - name: GigabitEthernet1
            ipv4:
              - address: 10.0.1.6/30
          - name: GigabitEthernet2
            ipv4:
              - address: 10.0.1.10/30
        state: merged
      when: inventory_hostname == "router2"
    - name: Configure ospf of Router 2
      ios_config:
        lines:
          - network 10.0.1.4 0.0.0.3 area 0
          - network 10.0.1.8 0.0.0.3 area 0
          - network 10.0.99.0 0.0.0.255 area 0
        parents: router ospf 1
      when: inventory_hostname == "router2"
    - name: No shutdown interfaces of Router 2
      ios_command:
        commands:
          - interface GigabitEthernet1
          - no shutdown
          - interface GigabitEthernet2
          - no shutdown
          - interface GigabitEthernet3
          - no shutdown
      when: inventory_hostname == "router2"