---
- name: Configure network devices
  hosts: switches
  gather_facts: no
  connection: network_cli
  tasks:
    - name: Configure vlan 10, 20 of switch 1
      ios_vlans:
        config:
          - name: vlan10
            vlan_id: 10
          - name: vlan20
            vlan_id: 20
        state: merged
      when: inventory_hostname == "switch1"
    - name: Configure trunk port of switch 1
      ios_l2_interfaces:
        config:
          - name: GigabitEthernet1/2
            mode: trunk
            trunk:
              encapsulation: dot1q
        state: merged
      when: inventory_hostname == "switch1"
    - name: Configure access port of switch 1
      ios_l2_interfaces:
        config:
          - name: GigabitEthernet1/0
            mode: access
            access:
              vlan: 10
          - name: GigabitEthernet1/1
            mode: access
            access:
              vlan: 10
        state: merged
      when: inventory_hostname == "switch1"
    # - name: Configure vlan 10, 20 of switch 2
    #   ios_vlans:
    #     config:
    #       - name: vlan10
    #         vlan_id: 10
    #       - name: vlan20
    #         vlan_id: 20
    #     state: merged
    #   when: inventory_hostname == "switch2"
    # - name: Configure trunk port of switch 2
    #   ios_l2_interfaces:
    #     config:
    #       - name: GigabitEthernet0/0
    #         mode: trunk
    #         trunk:
    #           encapsulation: dot1q
    #     state: merged
    #   when: inventory_hostname == "switch2"